---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: music-assistant
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: music-assistant
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      music-assistant:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: ghcr.io/music-assistant/server
              tag: 2.3.0@sha256:e83fc134b7a05dbea2c7a71da9dee8fe9006a04e71b97606e4155ce64e47a773
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probes
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8095
                  initialDelaySeconds: 30
                  periodSeconds: 10
                  timeoutSeconds: 1
                  failureThreshold: 3
              readiness: *probes
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 100m
                memory: 256Mi
              limits:
                memory: 1Gi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    service:
      app:
        type: LoadBalancer
        ipFamilyPolicy: PreferDualStack
        ipFamilies:
          - IPv4
          - IPv6
        annotations:
          io.cilium/lb-ipam-ips: "10.88.0.36,2402:21a0:2043:88::36"
        ports:
          http:
            port: *port
          stream:
            port: 8097
    route:
      app:
        hostnames: ["music-assistant.lumu.au"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: app
                port: *port
    persistence:
      config:
        existingClaim: music-assistant
        globalMounts:
          - path: /data
      music:
        existingClaim: media
        globalMounts:
          - path: /music
            subPath: music
            readOnly: true
