apiVersion: v1
kind: Secret
metadata:
    name: netbox-secret
stringData:
    db_password: ENC[AES256_GCM,data:HJiMUCf4XhOA+gi40RjZWnsfH6GJEZFRttQfWpCU8a4=,iv:tTahCdp+KbRFiaEwsvrHCMNB59iNkrPgxhG/OyPzXQg=,tag:gWLY2tdVsC6KAedOMMHZ1Q==,type:str]
    db_root_password: ENC[AES256_GCM,data:MTMX845ZxUkIp0yT4vncDHRUQlDZzA268jWwbbOKgi4=,iv:ubo8CMyeEkByCO7xMYGHV5mMU+p6rHTrfmSNi59t3NQ=,tag:Ia5QIOgYJMhhGbWcGqom3Q==,type:str]
    secret_key: ENC[AES256_GCM,data:SeLEI+s7i5SSv6/YeRMJf6Rmo023tf7F7XlAedqv+z4qJfhyv9RmzMrOmQ8bZZ13L7xjEzQMKx7L4EidkMwVpewZdQ==,iv:3mJWkMLLHAnWnDU9D8qWeekomBNMw7GTQQzStGTE2ow=,tag:b+rRfVKytAq0T6tFjhburg==,type:str]
    superuser_password: ENC[AES256_GCM,data:GUFiv/jsHik5EczjjEpAX9sknjICwQ==,iv:uQ1ht41edbzR9fINqzVpfMRWrVSZOh/iDlQUenyh3lM=,tag:2qvd8wCnygEI9MePsW70Ow==,type:str]
    superuser_api_token: ENC[AES256_GCM,data:Zgk9ew/DBEjDIpp/mhJqfRs5YaSPS+inUuEmY753JWQjBPKU/Fu8jw==,iv:BxIkZA5u6vqKT0lHIliO0CRk58mwENGVr6ltKHhzyAc=,tag:2Q1xQGzjRnUMxiG/z34IFQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFYTF6OURKUk5vV3MzLzE1
            SXQ4ZnpLUUlxc1Nib3A2ajlHRnNnOEdnbkZRCm5kNy92NTB6Mm94MU5EVnpWbmRa
            OVpPSW1lSWwrcDN3TUVWSjdlU3RCQ2cKLS0tIDNiRkZRUll1WmhWZzZmSDYzZHZJ
            WW8xU0JyR04zVnVUMnVsaUdBVVdlU2cK/9fcXBrjP4fv4oHuEOPJnA/8BoiJVp+f
            UhwOeJEtW0RbRRgWh0wLsuSaxXa1FhSIA8Nf4BG/7hzZFMYbjyEgpQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-26T13:55:46Z"
    mac: ENC[AES256_GCM,data:jWVPbk+6cVlm1pA1YfmaaY44BupQu1gX3cbSSUh92IaP/Yiwnuoe29wL3Wn50c17gzTThx0K2fg8SFeI3+nEPfLpsJ23GKEga/XYvHhW5zbvpXaDkiDhH6gsUtUGAy5tg0Vk4IX8r5qSYatIi5vkb+pWESfCjUU759igqx2I5xc=,iv:u/P8F11S2EnmLAlI0AkgdOr77bcxIgn6x1E9/Ra4p1A=,tag:++UhzREQJ9sfLIvncOE0Vg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
