---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: invidious
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: invidious
  values:
    controllers:
      invidious:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          invidious:
            image:
              repository: quay.io/invidious/invidious
              tag: 2.20260207.0@sha256:9d972ea5930c2e170b3c4d49bdd9fa09bf03f077d555f58747342062dffc5876
            env:
              TZ: Australia/Perth
            resources:
              requests:
                cpu: 50m
                memory: 256Mi
              limits:
                memory: 512Mi

      postgres:
        pod:
          securityContext:
            fsGroup: 999
            fsGroupChangePolicy: OnRootMismatch
        containers:
          postgres:
            image:
              repository: docker.io/library/postgres
              tag: 16-alpine
            env:
              POSTGRES_USER: invidious
              POSTGRES_DB: invidious
              POSTGRES_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: invidious-secret
                    key: POSTGRES_PASSWORD
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi

    service:
      invidious:
        controller: invidious
        ports:
          http:
            port: &port 3000
      postgres:
        controller: postgres
        ports:
          http:
            port: 5432

    route:
      invidious:
        hostnames: ["invidious.lumu.au"]
        parentRefs:
          - name: envoy-internal
            namespace: network
            sectionName: https
        rules:
          - backendRefs:
              - identifier: invidious
                port: *port

    persistence:
      data:
        existingClaim: invidious
        advancedMounts:
          postgres:
            postgres:
              - path: /var/lib/postgresql/data
                subPath: postgres
      config:
        type: secret
        name: invidious-secret
        advancedMounts:
          invidious:
            invidious:
              - path: /invidious/config/config.yml
                subPath: config.yml
      tmp:
        type: emptyDir
        advancedMounts:
          invidious:
            invidious:
              - path: /tmp
