---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: globalping-probe
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: globalping-probe-secret
    template:
      data:
        GP_ADOPTION_TOKEN: "{{ .GP_ADOPTION_TOKEN }}"
  dataFrom:
    - extract:
        key: globalping-probe
