---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: globalping-probe
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: globalping-probe

  values:
    controllers:
      globalping-probe:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: globalping/globalping-probe
              tag: 0.46.1@sha256:ab7f295adb948be03e3565bbd1fcc84862c4cf31af1edddbbac679a860b38edf
            envFrom:
              - secretRef:
                  name: globalping-probe-secret
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
            securityContext:
              allowPrivilegeEscalation: false
              capabilities:
                drop: ["ALL"]
                add: ["NET_RAW"]
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        runAsNonRoot: true
