---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app openclaw
  namespace: flux-system
spec:
  targetNamespace: openclaw
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  interval: 10m
  path: ./kubernetes/apps/openclaw/openclaw/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  dependsOn:
    - name: openclaw-operator
    - name: external-secrets-stores
