---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
  - ./ocirepository.yaml
configMapGenerator:
  - name: grafana-dovecot-dashboard
    files:
      - dovecot-native-metrics.json=./resources/dovecot-native-metrics.json
    options:
      labels:
        grafana_dashboard: "true"
      annotations:
        grafana_folder: default
generatorOptions:
  disableNameSuffixHash: true
