---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kometa
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: kometa
  values:
    controllers:
      kometa:
        type: cronjob
        cronjob:
          schedule: "0 4 * * *"
          backoffLimit: 0
          concurrencyPolicy: Forbid
          successfulJobsHistory: 1
          failedJobsHistory: 1
          ttlSecondsAfterFinished: 86400
        containers:
          app:
            image:
              repository: kometateam/kometa
              tag: v2.3.1@sha256:683c04827ef3fecf1cc5cb178f75f91f968aef6c6d89d34bc9c70966fd1d7259
            args:
              - --run
              - --read-only-config
              - --debug
              - --config
              - /config/config.yml
            env:
              TZ: ${TIMEZONE}
              KOMETA_PLEX_URL: http://plex.default.svc.cluster.local:32400
            envFrom:
              - secretRef:
                  name: kometa-secret
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: false
              capabilities: {drop: ["ALL"]}
            resources:
              requests:
                cpu: 10m
              limits:
                memory: 512Mi
        pod:
          restartPolicy: Never
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
    persistence:
      config:
        existingClaim: kometa
        globalMounts:
          - path: /config
      config-file:
        type: configMap
        name: kometa-configmap
        globalMounts:
          - path: /config/config.yml
            subPath: config.yml
            readOnly: true
      tmp:
        type: emptyDir
