---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lumu-ca-root
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lumu-ca-root
    creationPolicy: Owner
  data:
    - secretKey: ca.crt
      remoteRef:
        key: StepCA
        property: root-cert
