---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: grimmory-mariadb
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: grimmory-mariadb
  values:
    auth:
      database: grimmory
      username: grimmory
      existingSecret: grimmory-secret
      existingSecretPasswordKey: mariadb_password
      existingSecretRootPasswordKey: mariadb-root-password
    primary:
      podSecurityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop: ["ALL"]
        readOnlyRootFilesystem: false
      resources:
        requests:
          cpu: 100m
          memory: 256Mi
        limits:
          memory: 512Mi
      persistence:
        enabled: true
        size: 4Gi
