apiVersion: v1
kind: Secret
metadata:
    name: grimmory-secret
stringData:
    mariadb_password: ENC[AES256_GCM,data:p5q9gWY0+xsjhVlS/dgJeppR70erPEroboVSHUHyTkw=,iv:wpazQViQnemRiE6RPg1A0RfawVPXKxrvQMVnWI0/imE=,tag:5PI7LvTRZ/1z8O52tktegw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:0IHTL1LICGiJDV/QE0QS6+M1S3qMigsaXdwlCBs5fa8=,iv:CFWtIUdrUDk6/uZbPDE+sYC1RTPoByKFBcpaz59Da4s=,tag:EX/GZvQH08qjcyIi11JGGg==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:8ClrYZmmrK+iNXFC/SATY9kPyf5CqP/mC2e9RRvx5L8=,iv:nise0KYrKkSCeUK8gXZOxEwchf1tKeYJxtKlcd/BwFY=,tag:23mRuL8ZvdJFy7Juvf3hdA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWnpYT0ZVbHY2OUh6bVl4
            eXNLa1g4TnNpS2dzZnV5MFJDY3BLeEsyWHdrCmlUK1hDa2JCMXZUN2RReDN4czVr
            eDc0eG9wNUFaOWl4OGxBME5vdm1lWGcKLS0tIDdqcmNZazV2THVlKzhraVJvWk55
            akVERUNLcG5uKy8zWE10U2FGcncyVVkKZ7yFSkSSfX/kVlTRzlebWdDmxAet8RfZ
            tjnjVe8Vvbvp+sOlYxfRCgIQ1pzs2VK81OSw8Sl3Mou8QwVFIUXGFg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T15:01:38Z"
    mac: ENC[AES256_GCM,data:moYUQ8RcBc0pF8OHg51Gkkr0dHr/lsbumTuPJtXfSdJUKhD4uUOeU1GFrtMsjgQi7GQQ1TTKu/wrO8Sp7kc4lSOKaFIidyPOfXqPWRuxgpz6xruzia5wtEb54JhInkETKpjb82qt3e7NU2j0Bb6EhVKxpDtQ0ZQme+0Bg9vsv30=,iv:IMZ4onc3pxlqOOFz8h5BWDd10yvf2Q1WmIyF0UX4AgY=,tag:PiRkLVws/0RpDEnpda827g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
