---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: piped
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: piped-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        config.properties: |
          PORT:8080
          HTTP_WORKERS:2
          PROXY_PART:https://pipedproxy.lumu.au
          API_URL:https://pipedapi.lumu.au
          FRONTEND_URL:https://piped.lumu.au
          DISABLE_REGISTRATION:false
          COMPROMISED_PASSWORD_CHECK:false
          FEED_RETENTION:30
          RYD_PROXY_URL:https://ryd-proxy.kavin.rocks
          SPONSORBLOCK_SERVERS:https://sponsor.ajay.app
          hibernate.connection.url:jdbc:postgresql://piped-backend-postgres:5432/piped
          hibernate.connection.driver_class:org.postgresql.Driver
          hibernate.dialect:org.hibernate.dialect.PostgreSQLDialect
          hibernate.connection.username:piped
          hibernate.connection.password:{{ .db_password }}
        POSTGRES_PASSWORD: "{{ .db_password }}"
  dataFrom:
    - extract:
        key: piped
