---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/kustomization-kustomize-v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app netbox
  namespace: flux-system
spec:
  targetNamespace: selfhosted
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  components:
    - ../../../../components/volsync
  interval: 1h
  path: ./kubernetes/apps/selfhosted/netbox/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: false
  dependsOn:
    - name: rook-ceph-cluster
    - name: volsync
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 5Gi
  decryption:
    provider: sops
    secretRef:
      name: sops-age
