---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: waha
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: waha-secret
    template:
      data:
        WAHA_API_KEY: "{{ .WAHA_API_KEY }}"
        WAHA_DASHBOARD_USERNAME: "{{ .WAHA_DASHBOARD_USERNAME }}"
        WAHA_DASHBOARD_PASSWORD: "{{ .WAHA_DASHBOARD_PASSWORD }}"
  dataFrom:
    - extract:
        key: waha
