apiVersion: v1
kind: Secret
metadata:
    name: booklore-secret
stringData:
    mariadb_password: ENC[AES256_GCM,data:fTGZ4Ox8gSe2ALD++W4Nu1og0miAoamLzaycDkseQxY=,iv:ZMkc96lnYcYbGK9S2s9NpYL+0tyNB4MeqUM9F4RaUbc=,tag:ms5bYET2qHR0kdHn452PqQ==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:jAb0zZk9Ct2JR0MbviHA+fSEq1phqCY9d1e0sre/SOo=,iv:p7tNuSooc14FP9Ews5tfBAyFvVj/jfIRXwv+Ujsq5J8=,tag:8g7t0rC+hA8lJSw4vwNUWQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6eHRQbnk1aUY2N05BUkxG
            aGRwMFhvWWJ0M3lzem9kL0wrWGhHbUNtNDFFCnBiTFJ6MGJMN1FOejBRZEI1WkNH
            V2hRYnZiT0VlN3gyQS9kZ3k4aDNlYm8KLS0tIEd1Z0s2cEs3b3NYdnUzYzRrVXd6
            RkYvWTUzMkI1Q2JuWHloa1ZtcERSWkUKssNVdKh1mHvLNIco1YR7mKol+WgXG59n
            +RS6AVuPNIdfxXZaobaN76rVUe5t+VB+S9DgNamWZr1bgEJc80mQAQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:33:18Z"
    mac: ENC[AES256_GCM,data:gcjglpIzCPS9vFgkEL7GC+8yCAn/D2SCZFQugRgfrI0I6vOgQhxblBu5I9CMgc/rNtgb46K4VI4cR+rDTjsS57Z64hTkwXsgDKP3ZLXovcPNFss6QNaIeEubFsDjCwfCtTdPrvEhfPp2wnayXl4/9vMo0BAWS0kw9jIWfVVAN/g=,iv:7eqoRwH1eqqF1tJlokrQx2gr4U9WqfDzwB4xJSwT2Gc=,tag:3ERLzS1AuOD3szcxq62Wug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
