apiVersion: v1
kind: Secret
metadata:
    name: booklore-secret
stringData:
    mariadb_password: ENC[AES256_GCM,data:jwLuO6VrzfY6NcceZaUlpvUG8IrpptBWyncj4aey4VE=,iv:EgsMMJRI6p1FGMonUYzL8zHcLueIxwB7N7VqbB1ddVc=,tag:lVTmK0WNwd9+udB9wAhoOw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsWDBmRjVQTWZsNjFFSjds
            Uy9SMzh5RDNiRmRsUEtKWEg5USs0ajdmc3kwCkNUNGhXaWVVV3FTZWw3VE13RUw2
            eXgwSnNiTTJKSENzU1dSRXFLSW9sb1EKLS0tIC94UDNUZHl6R0ljdmt3N2poOC9x
            ZlFXUjZrNEJ6ajZ2K0lNMWNhWFgwWnMK4BR3WClRbEtyxOJrJT6vtIy4yNG4+yPC
            9L0E+d4mv6LXIWic8E0aWpzeJCphGhz00Z3SKqIzHmvGBucJnJwVGQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:18:31Z"
    mac: ENC[AES256_GCM,data:4ayHOfuEtIUb/w87kdPjdqbwnuFGSqdjsTu3M8kdRKZ+FhLp5SxqFVJfHxUeLkhjlH+u/ERShU3PLQ9zHB0365oRRv7n+dCx3qdNrRvAstAnXKF94LHFEu6b9UWiCj+Ag2ZtN1ezWEbwcCBBhaZRy2X1xOjCsreQwuUfiGYHL7I=,iv:fln48L2sUZ1Et6Z+C5nT+hSWMLA045zzgTMdLfm55nM=,tag:5zq+tcXC5n9u+UmnzPhPbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
