apiVersion: v1
kind: Secret
metadata:
    name: booklore-secret
stringData:
    mariadb_password: ENC[AES256_GCM,data:lXIWhuL0/d3x3jSMcBVBUGHwdEezkwQiHorosUdT9GI=,iv:316Lgn0BoPobHB1u2RrUYbc5hU0uB6fMc9ZNHVGJ+Sc=,tag:OP44pRSq44BtYMFBKtQraw==,type:str]
    mariadb-password: ENC[AES256_GCM,data:JMtdRYiMDV8spItIE1PfpWrYEg56kzawuBkj0wOO5Po=,iv:Ndd/H5m3Hap2DtvTsXzEZH+vfFFfEfx84BpYSD1GEYc=,tag:V3K7ndzWzbegRIfi/iZC/w==,type:str]
    mariadb-root-password: ENC[AES256_GCM,data:2v9tBLL2h8S08AaHBORbbKHicVkjwNRNQlJs8zE+Usw=,iv:cVF0WDnF4I/Baeie2E+/c4HpWUmtn2lzGgIWRNOQPlc=,tag:M+Dkd0clP6lKPzU9QCv+yQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1zucujcrr89pecplrme76f4vxcc05lg3hm8849mmfggvcvcv4ppls7cquw8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvM21pS0NHdmQ1NW1tanZu
            ZVJjNWp2RTVHU1ZCVi9LeDU1eTg4N1BpQWgwCmVkb01ZL0o3ZGs4SEZ2Y1BZQVVB
            TUpDeEQvZStWNDcxdzZJRmUyclpSRUkKLS0tIHd3citMNU92YjZzWExycU5XZ2ky
            bXY4bkxSUk1zMjd2K1RXd09PZUs0OTAKFXdSZuDfMF9RiqK66R2+/dlxn3H/4zUZ
            3IGfhPvbf+D2G4+V6Qz4Nr6hca42cFLe//Kc7lHvbTr7698sZb5dmA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-21T14:41:16Z"
    mac: ENC[AES256_GCM,data:BTV0zCJVZelRLXLDU/JBvB4ym99mBaQg0j+6/oZdNXzqog9XOW9q+it4eUqXXLV2r3WYlDGKu0sE7+zp4XIxPo2pFJ5G2jX9pi/s9Olc+jlSVhA0+s7tNgY5QNiHlki+ONF26u4cYbWizFu+gIj+hYwFyb5QewupSXnFn1XZ1SE=,iv:d40RSc2BSOTwlDJUplJBUKTR57ae05tVGbIa94/oPG0=,tag:62ZQT3omQTpxp9WQH+YpRQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
