---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mumble
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: mumble-secret
    template:
      engineVersion: v2
      data:
        MUMBLE_SUPERUSER_PASSWORD: "{{ .SUPERUSER_PASSWORD }}"
  dataFrom:
    - extract:
        key: mumble
