---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: mumble
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: mumble
  dependsOn:
    - name: rook-ceph-cluster
      namespace: rook-ceph
  values:
    controllers:
      mumble:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: mumblevoip/mumble-server
              tag: latest@sha256:631115dfc5ce17f89c63d33b57627b52eba1ffa5ff03eb09df8765f49a639d9c
            env:
              TZ: Australia/Perth
            envFrom:
              - secretRef:
                  name: mumble-secret
              - configMapRef:
                  name: mumble-config
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false

    defaultPodOptions:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
        fsGroupChangePolicy: OnRootMismatch

    service:
      app:
        type: LoadBalancer
        annotations:
          lbipam.cilium.io/ips: 10.88.0.37
        ports:
          voice-tcp:
            port: 64738
            protocol: TCP
          voice-udp:
            port: 64738
            protocol: UDP

    persistence:
      data:
        existingClaim: mumble
        globalMounts:
          - path: /data
      tls:
        type: secret
        name: mumble-tls
        globalMounts:
          - path: /certs
            readOnly: true
