dynamic_collections:
  TMDb Collections:
    type: tmdb_collection
    remove_suffix: Collection
    remove_prefix: The
    template: tmdb_franchise

templates:
  tmdb_franchise:
    tmdb_collection_details: <<value>>
    collection_mode: show_items
    collection_order: release
    minimum_items: 2
    sync_mode: sync
