---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openclaw-api-keys
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: openclaw-api-keys
  data:
    - secretKey: TELEGRAM_BOT_TOKEN
      remoteRef:
        key: openclaw
        property: TELEGRAM_BOT_TOKEN
    - secretKey: BRAVE_API_KEY
      remoteRef:
        key: openclaw
        property: BRAVE_API_KEY
    - secretKey: OPENCLAW_AUTH_TOKEN
      remoteRef:
        key: openclaw
        property: OPENCLAW_AUTH_TOKEN
