---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./externalsecret-gateway-token.yaml
  - ./externalsecret-media.yaml
  - ./instance.yaml
  - ./networkpolicy.yaml
  - ./route.yaml
