---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: renovate-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RENOVATE_GITHUB_APP_ID: "{{ .github_app_id }}"
        RENOVATE_GITHUB_APP_KEY: "{{ .github_app_key }}"
        RENOVATE_GITHUB_TOKEN: "{{ .github_token }}"
        RENOVATE_GITLAB_TOKEN: "{{ .gitlab_token }}"
  dataFrom:
    - extract:
        key: renovate
      rewrite:
        - regexp:
            source: "(.*)"
            target: "$1"
