---
# yaml-language-server: $schema=https://schemas.recyclarr.dev/v8/config-schema.json
sonarr:
  series:
    base_url: http://sonarr.default.svc.cluster.local
    api_key: !env_var SONARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      series: plex-imdb
      season: default
      episodes:
        rename: true
        standard: default
        daily: default
        anime: default
    quality_definition:
      type: series
    quality_profiles:
      - trash_id: 72dae194fc92bf828f32cde7744e51a1 # WEB-1080p
        name: WEB-1080p
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: 158188097a58d7687dee647e04af0da3 # [Required] Golden Rule HD
          select:
            - 47435ece6b99a0b477caf360e79ba0bb # x265 (HD)
        - trash_id: f4a0410a1df109a66d6e47dcadcce014 # [Optional] Miscellaneous
          select:
            - 32b367365729d530ca1c124a0b180c64 # Bad Dual Groups
            - 82d40da2bc6923f41e14394075dd4b03 # No-RlsGroup
            - e1a997ddb54e3ecbfe06341ad323c458 # Obfuscated
            - 06d66ab109d4d2eddb2794d21526d140 # Retags
            - 1b3994c551cbb92a2c781af061f4ab44 # Scene

radarr:
  movies:
    base_url: http://radarr.default.svc.cluster.local
    api_key: !env_var RADARR_API_KEY
    delete_old_custom_formats: true
    media_management:
      propers_and_repacks: do_not_prefer
    media_naming:
      folder: plex-imdb
      movie:
        rename: true
        standard: plex-imdb
    quality_definition:
      type: movie
    quality_profiles:
      - trash_id: 9ca12ea80aa55ef916e3751f4b874151 # Remux + WEB 1080p
        name: Remux + WEB 1080p
        reset_unmatched_scores:
          enabled: true
    custom_format_groups:
      add:
        - trash_id: f8bf8eab4617f12dfdbd16303d8da245 # [Required] Golden Rule HD
          select:
            - dc98083864ea246d05a42df0d05f81cc # x265 (HD)
        - trash_id: 9337080378236ce4c0b183e35790d2a7 # [Optional] Miscellaneous
          select:
            - b6832f586342ef70d9c128d40c07b872 # Bad Dual Groups
            - ae9b7c9ebde1f3bd336a8cbd1ec4c5e5 # No-RlsGroup
            - 7357cf5161efbf8c4d5d0c30b4815ee2 # Obfuscated
            - 5c44f52a8714fdd79bb4d98e2673be1f # Retags
            - f537cf427b64c38c8e36298f657e4828 # Scene
        - trash_id: f4f1474b963b24cf983455743aa9906c # [Optional] Movie Versions
          select:
            - 570bc9ebecd92723d2d21500f4be314c # Remaster
            - eca37840c13c6ef2dd0262b141a5482f # 4K Remaster
            - e0c07d59beb37348e975a930d5e50319 # Criterion Collection
            - 9d27d9d2181838f76dee150882bdc58c # Masters of Cinema
            - 09d9dd29a0fc958f9796e65c2a8864b4 # Open Matte
            - db9b4c4b53d312a3ca5f1378f6440fc9 # Vinegar Syndrome
            - 957d0f44b592285f26449575e8b1167e # Special Edition
            - e9001909a4c88013a359d0b9920d7bea # Theatrical Cut
            - 0f12c086e289cf966fa5948eac571f44 # Hybrid
            - eecf3a857724171f968a66cb5719e152 # IMAX
            - 9f6cbff8cfe4ebbc1bde14c7b7bec0de # IMAX Enhanced
    custom_formats:
      - trash_ids:
          - bfd8eb01832d646a0a89c4deb46f8564 # Upscaled (not in any CF group)
        assign_scores_to:
          - name: Remux + WEB 1080p
